surrealdb/surrealist

.vscode/settings.json, frontend/src/components/Scaffold/index.tsx, frontend/src/components/Settings/index.tsx, frontend/src/components/TabBar/index.tsx
Simple QOL update by adding `autoComplete="off"` and `spellCheck="false"` to text inputs.
=> Disable autocomplete

backend/database.go, frontend/src/components/ConsolePane/index.tsx, frontend/src/components/Scaffold/index.tsx, frontend/src/components/Scaffold/style.module.scss, frontend/src/store.tsx, frontend/src/typings.d.ts, frontend/src/util/database.tsx
So I added a console output pane to the app which looks like:
There is a few issues, but it's working nicely
Most of my issues are due to lack of experience with react/mantine/project architecture 
- Was unsure how to make this pane minimizable, some of the base is already there for this though
- Coloring is kinda screwed, I had to use a package "ansi-to-html" to convert this output to a html string which uses sometimes bad colors, I did a add one conversion though, so it could be extended(assuming sdb sticks to an output color scheme)
- I'm not sure if this should only show for a selected tab/when running the server, i think it's global atm
=> Add console output/pane for database output

README.md, src-tauri/src/database/shell.rs
Hi Surrealist team,
this is juste littles fixes on build_start_command (for linux/macos) to dev with tauri, README updated.
Thank you.
=> Fixes dev tauri

src/components/Scaffold/index.tsx, src/views/authentication/AccountsPane/index.tsx
In the surrealist password fields ware just TextInput. I changed to PasswordInput for security.
Passwords to database or auth ware quite visible and anyone in public could lookup the passwords.
Thank you for making Surrealist.
=> Use PasswordInput in password fields

src-tauri/build.rs, src-tauri/src/config.rs, src-tauri/src/database/mod.rs, src-tauri/src/database/shell.rs, src-tauri/src/main.rs, src-tauri/src/query.rs, src-tauri/src/schema.rs
This PR fixes multiple Clippy warnings.
This PR also fixes formatting in `src-tauri`.
=> FIX multiple `Clippy` warnings to improve code quality.

.github/workflows/ci.yml
This workflow checks, tests and lints `src-tauri` ensuring the correctness of the code.
=> [CI] Add Github Action to run on `push` and `pull_request`.

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src/views/query/ResultPane/index.tsx
This PR updates the SurrealDB crate to the latest commit, and improves styling for the component rendering errors in the output pane of the query tool. This all, to properly implement the new error messaging format in SurrealDB.
In addition, I slightly improved the row counting logic
=> Update SurrealDB; Improved error messages

src-embed/Cargo.lock, src-embed/Cargo.toml, src-embed/src/query/local.rs, src-embed/src/query/mod.rs, src-embed/src/query/remote.rs, src-tauri/Cargo.lock, src-tauri/tauri.conf.json, src/generated/surrealist-embed.d.ts, src/generated/surrealist-embed.js, src/generated/surrealist-embed_bg.wasm.d.ts
I additionally simplified the `process_result` method a bit
=> Switch to `surrealdb-beta` crate to use official `QueryStats`-API

src/views/authentication/AccountsPane/index.tsx
=> fix: comment icon in authentication view was to big

src/components/ConnectionDetails/index.tsx, src/components/Scaffold/modals/signup.tsx, src/connection.tsx, src/constants.tsx, src/types.tsx, src/util/commands.tsx, src/util/helpers.tsx, src/util/intents.tsx, src/views/authentication/ScopesPane/index.tsx, src/views/query/QueryPane/index.tsx
- Accessible from the authentication view
- Automatically infers variables from the signup query
- Intents and commands for convenience
=> Add manual scope registration

README.md
Fixed a minor grammar issue where there should be a period instead of a comma.
=> Minor grammar fix in README

pnpm-lock.yaml, src/components/ConnectionDetails/index.tsx, src/components/Inputs/index.tsx, src/components/Scaffold/mini/new.tsx, src/components/Scaffold/modals/palette.tsx, src/components/Scaffold/modals/signup.tsx, src/components/Scaffold/modals/table.tsx, src/components/Scaffold/settings/tabs/Serving.tsx, src/components/Toolbar/components/Connections/index.tsx, src/components/Toolbar/index.tsx, src/views/authentication/AccountsPane/index.tsx, src/views/authentication/ScopesPane/index.tsx, src/views/designer/DesignDrawer/elements/changefeed.tsx, src/views/designer/DesignDrawer/elements/events.tsx, src/views/designer/DesignDrawer/elements/fields.tsx, src/views/designer/DesignDrawer/elements/indexes.tsx, src/views/designer/DesignDrawer/index.tsx, src/views/explorer/CreatorDrawer/index.tsx, src/views/explorer/ExplorerPane/index.tsx, src/views/explorer/TablesPane/index.tsx, src/views/functions/EditorPanel/index.tsx, src/views/functions/FunctionsPanel/index.tsx, src/views/functions/FunctionsView/index.tsx, src/views/models/ModelsPanel/index.tsx, src/views/query/HistoryDrawer/index.tsx, src/views/query/QueryView/index.tsx, src/views/query/SavesDrawer/index.tsx
Spellchecking in the text input is frustrating.
=> feat: disable spell checking in text inputs

src/components/Inputs/index.tsx
Fixes the improper visual requirement of "Field kind" in the fields section of the table designer
=> fix: improper requirement of field kind

package.json, pnpm-lock.yaml, tsconfig.node.json, vite.config.embedded.ts, vite.config.ts
Fixes https://github.com/surrealdb/surrealist/issues/328
=> chore: enable gzip compression

src/screens/database/toolbar.tsx, src/screens/database/views/functions/EditorPanel/index.tsx, src/screens/database/views/functions/FunctionsView/index.tsx
This PR is related to issue #374. I was finding myself wanting to be able to easily format functions directly in the function editor. I decided to implement this myself, as well as format the function on load (not sure if we want to do this, or if we should do it in a different way).
=> feat: #374 format function editor

src/screens/database/views/designer/TableGraphPane/helpers.tsx
This marks edges and nodes in the graph als not deletable
Closes #392
=> fix: prevent deleting edges and nodes

src/components/DataTable/datatypes.tsx
=> fix(geo type): use raw geopoint for invalid or "null island" coordinates

src-tauri/src/database/mod.rs, src/assets/styles/override.scss, src/components/App/modals/connection.tsx, src/components/App/settings/tabs/Serving.tsx, src/hooks/schema.ts, src/screens/cloud-manage/api/auth.tsx, src/screens/cloud-manage/pages/Instances/modals/creator.tsx, src/screens/database/connection/connection.tsx, src/screens/database/connection/surreal.tsx, src/screens/database/views/graphql/GraphqlView/index.tsx, src/screens/database/views/graphql/QueryPane/index.tsx, src/types.tsx, src/util/mantine.tsx
- Fixed connection editor not loading contents on initial open
- Fixed T&C always prompting
- Fixed SurrealKV storage engine not working for database serving
- Fixed missing "function" kind in kind inputs
- Prevent dismissing of the instance creator
- Display whether GraphQL is enabled on the remote instance
- Enable GraphQL for local database serving
=> General beta improvements

src/providers/Designer/helpers.tsx
Saving a relation table caused incoming and outgoing tables to be overwritten by the in/out field types. This PR forces any present in/out fields to be set to the incoming/outgoing tables on save.
Fixes #426
=> Fixed define field in/out overwriting table relations

package.json, src/assets/changelogs/3.0.2.md, src/util/migrator.tsx
- Bumped the minimum version to SurrealDB 2.0.0 stable
- Fixed initialization error
=> Release 3.0.2

src/components/App/modals/connection.tsx
=> Fix multiple new connections using the same id

src/components/ConnectionDetails/index.tsx
=> Fix missing "add access field" button

src/providers/Designer/helpers.tsx
=> Include READONLY in output

src/screens/database/docs/index.tsx, src/screens/database/docs/topics/authentication/access-user-data.tsx, src/screens/database/docs/topics/authentication/sign-in.tsx, src/screens/database/docs/topics/authentication/sign-up.tsx, src/screens/database/docs/topics/concepts/full-text-search.tsx, src/screens/database/docs/topics/concepts/surrealml.tsx, src/screens/database/docs/topics/global/databases.tsx, src/screens/database/docs/topics/global/initialize.tsx, src/screens/database/docs/topics/global/introduction.tsx, src/screens/database/docs/topics/global/namespaces.tsx, src/screens/database/docs/topics/schema/analyzers.tsx, src/screens/database/docs/topics/schema/functions.tsx, src/screens/database/docs/topics/schema/params.tsx, src/screens/database/docs/topics/schema/scopes.tsx, src/screens/database/docs/topics/schema/users.tsx
Noticed some low-hanging fruit in the API docs so have put together a PR. Also updates Rust to use record users instead of scopes.
=> Rephrase some parts of the API docs

src/screens/database/views/graphql/QueryPane/index.tsx
Tiny suggested rewording for the "GraphQL is not enabled..." message.
=> Tiny GraphQL message rewording

src/adapter/mini.tsx, src/constants.tsx, src/hooks/dataset.ts, src/screens/database/toolbar.tsx, src/startup/mini-run.tsx, src/types.tsx, src/util/messaging.tsx, src/util/surrealql.tsx
- Notify parent window of ready status
- Allow loading any official dataset path
=> Improve mini functionality

src/editor/commands.tsx, src/editor/graphql.tsx, src/editor/keymaps.tsx, src/editor/query.tsx, src/screens/database/views/graphql/GraphqlView/index.tsx, src/screens/database/views/query/QueryPane/index.tsx, src/screens/database/views/query/QueryView/index.tsx, src/screens/database/views/query/ResultPane/index.tsx, src/screens/database/views/query/ResultPane/preview.tsx, src/screens/database/views/query/VariablesPane/index.tsx
=> Execute queries from the variables panel

src/screens/database/views/explorer/ExplorerPane/hooks.tsx, src/screens/database/views/explorer/ExplorerView/index.tsx
=> Escape explorer table names

src/adapter/mini.tsx, src/components/App/modals/data-export.tsx, src/components/CodePreview/index.tsx, src/components/CodeSnippet/index.tsx, src/components/DriverSelector/index.tsx, src/components/DriverSelector/style.module.scss, src/constants.tsx, src/screens/cloud-manage/components/InstanceType/index.tsx, src/screens/cloud-manage/hooks/billing.tsx, src/screens/cloud-manage/hooks/invoices.tsx, src/screens/cloud-manage/modals/billing.tsx, src/screens/cloud-manage/pages/Billing/index.tsx, src/screens/cloud-manage/pages/Instances/modals/connect-cli.tsx, src/screens/cloud-manage/pages/Instances/modals/connect-sdk.tsx, src/screens/database/components/ConnectionStatus/index.tsx, src/screens/database/docs/style.module.scss, src/screens/database/docs/topics/global/introduction.tsx, src/screens/database/toolbar.tsx, src/screens/database/views/designer/TableGraphPane/index.tsx, src/screens/database/views/explorer/ExplorerView/index.tsx, src/screens/database/views/functions/EditorPanel/index.tsx, src/screens/database/views/query/QueryPane/index.tsx, src/screens/database/views/query/QueryView/index.tsx, src/screens/database/views/query/ResultPane/index.tsx, src/screens/database/views/query/VariablesPane/index.tsx, src/screens/mini-new/index.tsx, src/screens/mini-run/index.tsx, src/startup/mini-run.tsx, src/types.tsx, src/util/drivers.tsx
=> Misc improvements

package.json, pnpm-lock.yaml, src/components/App/index.tsx, src/components/App/modals/connections.tsx, src/components/App/modals/documentation.tsx, src/components/App/modals/hotkeys.tsx, src/components/App/modals/palette.tsx, src/components/App/style.module.scss, src/hooks/keys.ts, src/types.tsx, src/util/commands.tsx, src/util/intents.tsx
- Adds a new documentation search modal
- Accessible through "Open SurrealDB Documentation" command and cmd + J shortcut
- Works identical to search in the docs
- Also altered the appearance of the command palette and connection list modals
=> Integrated documentation searching

src/screens/database/components/DatabaseList/index.tsx, src/screens/database/components/NamespaceList/index.tsx, src/types.tsx
Replace "Select namespace/database" with "Create namespace/database" when none is available yet
=> Improve namespace/database creation

src/constants.tsx, src/screens/database/connection/connection.tsx, src/screens/database/views/query/HistoryDrawer/index.tsx, src/screens/database/views/query/HistoryDrawer/style.module.scss, src/screens/database/views/query/QueryPane/index.tsx
- Limit maximum size of entries
- Truncate large previews
- Improve UX
Future:
- Customize limits
=> Improve query history

src/adapter/base.tsx, src/adapter/browser.tsx, src/adapter/desktop.tsx, src/adapter/index.tsx, src/adapter/mini.tsx
=> Fix dev builds

src/components/App/modals/data-export.tsx, src/components/App/modals/register.tsx, src/components/App/modals/signup.tsx
=> Fix possible active connection errors

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/main.rs, src-tauri/src/open.rs, src-tauri/src/paths.rs, src-tauri/src/whitelist.rs, src/adapter/base.tsx, src/adapter/browser.tsx, src/adapter/desktop.tsx, src/adapter/mini.tsx, src/components/App/hooks/window.tsx, src/components/App/modals/hotkeys.tsx, src/screens/database/views/explorer/ExplorerPane/index.tsx, src/screens/database/views/query/HistoryDrawer/index.tsx, src/screens/database/views/query/QueryPane/index.tsx, src/screens/database/views/query/QueryView/index.tsx, src/screens/database/views/query/QueryView/strategy.tsx, src/screens/database/views/query/ResultPane/index.tsx, src/screens/database/views/query/ResultPane/previews/index.tsx, src/screens/database/views/query/SavesDrawer/index.tsx, src/screens/database/views/query/TabsPane/index.tsx, src/stores/config.tsx, src/stores/query.tsx, src/types.tsx, src/util/commands.tsx, src/util/config.tsx, src/util/defaults.tsx, src/util/helpers.tsx, src/util/messaging.tsx, src/util/migrator.tsx
- Allow opening .surql files as query tabs in Surrealist
- Synchronised with the file system
- File paths are whitelisted for added security
=> File system based query tabs

src/screens/database/views/functions/FunctionsView/index.tsx
=> Allow uppercase function names

src/modals/table-definition.tsx, src/screens/database/components/TablesPane/index.tsx, src/screens/database/views/explorer/ExplorerView/index.tsx
Added a context menu option to generate and show a full table definition, including fields, indexes, and events
=> Show table definition

src-tauri/src/main.rs
Attempted solution for #276 by setting the environment flag on startup
=> Forcefully configure WEBKIT_DISABLE_DMABUF_RENDERER

src/screens/database/views/explorer/ExplorerPane/hooks.tsx
=> Correctly parse explorer field idents

src/util/schema.tsx
=> Batch tables during schema sync

src/components/App/hooks/routing.tsx, src/components/App/modals/sandbox.tsx, src/screens/cloud-panel/components/Instance/index.tsx, src/screens/cloud-panel/components/Instance/modals/change-type.tsx, src/screens/cloud-panel/components/InstanceType/index.tsx, src/screens/cloud-panel/modals/connect-curl.tsx, src/screens/cloud-panel/pages/Billing/index.tsx, src/screens/cloud-panel/pages/Chat/copilot.tsx, src/screens/cloud-panel/pages/Instances/index.tsx, src/screens/cloud-panel/pages/Provision/steps/4_type.tsx, src/screens/database/sidebar.tsx
- Added a new interactive "HTTP cURL" connection example
- Fixed cloud navigation button not highlighting in the sidebar
- Fixed potential redirecting issues
- Display instance type categories on instance cards
- Improved the instance type selection UI
=> Surreal Cloud panel improvements

src/util/migrator.tsx
Resolves instances where "Session unavailable" was thrown when the active connection was invalid
=> Fallback to sandbox when connection is missing

src/components/ActionBar/account.tsx, src/components/ActionButton/index.tsx, src/components/Embedder/index.tsx, src/components/NavigationIcon/index.tsx, src/screens/surrealist/sidebar.tsx, src/screens/surrealist/toolbar.tsx, src/screens/surrealist/views/authentication/LevelPanel/index.tsx, src/screens/surrealist/views/query/ResultPane/index.tsx
This PR fixes a few bugs with the last PR I created, as well as added a small open delay to tooltips. This PR also fixes a small bug where the navigation to the start page would not close the sidebar on mobile.
=> update: misc fixes

src/adapter/browser.tsx, src/components/App/modals/connections.tsx, src/schemas.tsx, src/types.tsx
This PR adds the ability to collapse groups in the connections modal.
=> feat: connection group collapsing

src/assets/styles/override.scss, src/components/ActionButton/index.tsx, src/components/App/modals/provisioning.tsx, src/components/App/style.module.scss, src/components/CodePreview/index.tsx, src/components/DataTable/style.module.scss, src/components/DriverSelector/index.tsx, src/components/Entry/style.module.scss, src/components/Introduction/index.tsx, src/components/Pane/index.tsx, src/components/Pane/style.module.scss, src/components/Slab/style.module.scss, src/screens/surrealist/cloud-panel/components/CategoryPicker/index.tsx, src/screens/surrealist/cloud-panel/components/Instance/modals/change-type.tsx, src/screens/surrealist/cloud-panel/components/InstanceType/index.tsx, src/screens/surrealist/cloud-panel/components/InstanceType/style.module.scss, src/screens/surrealist/cloud-panel/components/Tile/style.module.scss, src/screens/surrealist/cloud-panel/pages/Referral/index.tsx, src/screens/surrealist/cloud-panel/style.module.scss, src/screens/surrealist/docs/topics/global/introduction.tsx, src/screens/surrealist/index.tsx, src/screens/surrealist/start/style.module.scss, src/screens/surrealist/views/designer/TableGraphPane/index.tsx, src/screens/surrealist/views/explorer/ExplorerPane/index.tsx, src/screens/surrealist/views/query/TabsPane/index.tsx, src/util/mantine.tsx
=> Redesign dark theme

src/screens/surrealist/views/query/ResultPane/previews/graph.tsx
Use backwards compatible SurrealQL syntax
=> Graph compatibility

src/components/App/modals/highlight-tool.tsx, src/util/highlighting.tsx
=> Improve highlight tool

src/screens/surrealist/views/query/ResultPane/index.tsx
Adds a new CSV export button in the Query view when the `Table` mode is selected.
Note: it will only work with simple data types like `bool`, `number`, `string`, etc..
=> Export data table as CSV

src/screens/surrealist/cloud-panel/modals/connect-sdk.tsx
This PR improves cloud code snippets
=> Update Cloud snippets

src/assets/styles/override.scss, src/components/App/globals.tsx, src/components/App/hooks/intercom.tsx, src/components/App/hooks/policy.tsx, src/components/App/modals/provisioning.tsx, src/components/App/modals/updater.tsx, src/components/Scaffold/index.tsx, src/util/helpers.tsx
=> Policy notification

src/cloud/mutations/capabilities.tsx, src/screens/surrealist/views/dashboard/ConfiguratorDrawer/capabilities/boolean.tsx, src/screens/surrealist/views/dashboard/ConfiguratorDrawer/capabilities/fixed-rule-set.tsx, src/screens/surrealist/views/dashboard/ConfiguratorDrawer/capabilities/free-rule-set.tsx, src/screens/surrealist/views/dashboard/ConfiguratorDrawer/capabilities/registry.tsx, src/screens/surrealist/views/dashboard/ConfiguratorDrawer/capabilities/shared.tsx, src/screens/surrealist/views/dashboard/ConfiguratorDrawer/configs/capabilities.tsx, src/types.tsx, src/util/helpers.tsx
=> Implement Cloud instance capability customization

src/assets/styles/override.scss, src/cloud/mutations/storage.tsx, src/screens/surrealist/pages/Billing/index.tsx, src/screens/surrealist/views/dashboard/ConfiguratorDrawer/configs/storage.tsx, src/screens/surrealist/views/dashboard/ConfiguratorDrawer/index.tsx, src/types.tsx
=> Implement Cloud instance disk size increasing

src/components/App/modals/data-import.tsx, src/components/Inputs/index.tsx, src/providers/Commands/keybindings.tsx
=> Enhanced CSV import

src/adapter/base.tsx, src/adapter/browser.tsx, src/adapter/desktop.tsx, src/components/App/modals/data-import.tsx
Fixes https://github.com/surrealdb/surrealist/issues/679
=> Implement JSON import & improve CSV import performance

src/components/App/modals/connections.tsx, src/hooks/connection.ts, src/screens/surrealist/pages/Overview/index.tsx
This PR introduces a more robust label management system with enhanced matching capabilities:
- Multiple label selection support
- Connection visibility toggle based on matches
- Two matching methods:
- **Any**: Displays connections matching any selected label
- **All**: Displays only connections containing all selected labels
=> Additional connection filtering options

src-tauri/src/open.rs, src/cloud/modals/connect-sdk.tsx
=> Fix incorrect Rust SDK snippet

src/providers/Designer/helpers.tsx
Escape event and index names in the Table Designer
Fixes #762
=> Fix missing ident escaping

package.json, src/assets/changelogs/3.3.2.md, src/cloud/queries/backups.tsx, src/components/InstanceActions/index.tsx, src/screens/surrealist/pages/Overview/content/instance.tsx, src/screens/surrealist/views/dashboard/DashboardView/index.tsx
=> Release 3.3.2

src/assets/styles/override.scss, src/cloud/queries/referral.tsx, src/components/ActionBar/account.tsx, src/components/App/hooks/intercom.tsx, src/components/EstimatedCost/index.tsx, src/components/InstanceTypes/index.tsx, src/components/Sidekick/index.tsx, src/hooks/cloud.ts, src/screens/surrealist/pages/CreateInstance/form.tsx, src/screens/surrealist/pages/CreateInstance/steps/compute.tsx, src/screens/surrealist/pages/CreateInstance/steps/organization.tsx, src/screens/surrealist/pages/CreateInstance/steps/storage-class.tsx, src/screens/surrealist/pages/CreateInstance/steps/storage-mode.tsx, src/screens/surrealist/pages/CreateInstance/steps/storage-size.tsx, src/screens/surrealist/pages/CreateInstance/steps/type.tsx, src/screens/surrealist/pages/CreateInstance/types.tsx, src/screens/surrealist/pages/Organizations/organization.tsx, src/screens/surrealist/views/dashboard/ConfigurationBlock/index.tsx, src/screens/surrealist/views/dashboard/ConfiguratorDrawer/configs/type.tsx, src/screens/surrealist/views/dashboard/ConfiguratorDrawer/index.tsx, src/screens/surrealist/views/dashboard/DiskUsageBlock/index.tsx, src/stores/cloud.tsx, src/types.tsx, src/util/cloud.tsx, src/util/helpers.tsx
Allow the creation and configuration of distributed cloud instances
=> Distributed instance creation

src/cloud/api/auth.tsx, src/cloud/api/index.tsx, src/cloud/api/version.tsx, src/components/App/index.tsx, src/components/App/modals/failed-connect.tsx, src/components/Pagination/index.tsx, src/screens/surrealist/views/explorer/ExplorerPane/index.tsx, src/stores/cloud.tsx
This PR fixes the overview page being unavailable without an internet connection. Additionally, this PR adds a dialog shown when a connection to Surreal Cloud can't be established (such as having no internet) which indicates to the user that they are not connected to Surreal Cloud and that features may be unavailable because of it.
Additionally this PR also fixes reused keys in the explorer view and a bug where the page in the record explorer is 0 on the first load.
Closes #789
=> Fix overview page being unusable without internet & other misc fixes

src/screens/surrealist/components/ConnectionStatus/index.tsx, src/screens/surrealist/views/explorer/ExplorerView/index.tsx
This PR fixes a bug where you could process an import or export without a namespace or database being selected, resulting in an error that is not present to the user.
=> Fix importing while no namespace or database is selected

src/components/App/modals/newsfeed.tsx, src/components/App/style.module.scss
- Fix: horizontal scroll possible on the article drawer view
=> Fix article scrollview

bun.lock, package.json, src-tauri/src/config.rs, src/adapter/desktop.tsx, src/assets/changelogs/3.4.1.md, src/stores/cloud.tsx, src/stores/config.tsx, src/styles/markdown.module.css, src/util/cloud.tsx, src/util/config.tsx
=> Release 3.4.1

src/cloud/queries/metrics.tsx, src/screens/surrealist/metrics/BaseAreaChart/index.tsx, src/screens/surrealist/metrics/HTTPRequestsChart/index.tsx, src/screens/surrealist/metrics/RPCRequestsChart/index.tsx, src/screens/surrealist/views/monitor/LogPane/index.tsx, src/screens/surrealist/views/monitor/MetricPane/metrics/connections.tsx, src/types.tsx
- RPC Requests/s
- HTTP Requests/s
=> Add connection metrics

src/screens/surrealist/views/monitor/LogPane/chart.tsx, src/screens/surrealist/views/monitor/LogPane/index.tsx
- Sort logs from oldest to newest
- Automatically scroll to the latest log line
- Shift the chart column to prioritize new lines
=> Improve logs behaviour

src/components/CloudAdminGuard/index.tsx, src/screens/surrealist/pages/OrganizationDeploy/index.tsx, src/screens/surrealist/views/dashboard/DashboardView/index.tsx, src/screens/surrealist/views/dashboard/DiskUsageBlock/index.tsx
Fixed a bug where organization members could access the deploy flow and upgrade flow
=> Fix cloud organization permissions

src/cloud/mutations/node.tsx, src/screens/surrealist/views/dashboard/UpgradeDrawer/configs/nodes.tsx, src/screens/surrealist/views/dashboard/UpgradeDrawer/configs/storage.tsx, src/screens/surrealist/views/dashboard/UpgradeDrawer/index.tsx
- Added the possibility to upgrade compute nodes of your cloud instance on the scale and dedicated plan.
=> Feature: Upgrade compute nodes

src/components/Sidekick/chat/index.tsx, src/components/Sidekick/chat/message.tsx
This PR fixes theming issues in the sidekick component. Fixes #924
=> Fix theming in sidekick component

src/components/HelpCenter/index.tsx, src/screens/surrealist/pages/Overview/index.tsx
This PR fixes problems with the Sidekick links within Surrealist after the Sidekick rewrite
=> Fix Sidekick links

src/components/ActionBar/sidekick.tsx
Fixes the Sidekick tooltip clipping under the menu bar on Windows
=> Fix sidekick tooltip

bun.lock, package.json, src/assets/styles/override.scss, src/components/MarkdownContent/index.tsx, src/components/Sidekick/chat/message.tsx
This PR makes two changes which improve Sidekick:
- Makes sources collapsed by default
- Implements GFM (GitHub Flavored Markdown) to support responses such as tables.
=> Sidekick improvements

src/components/GeographyDrawer/index.tsx
the (long, lat) below the map now reads Longitude: {long val} Latitude: {lat val}, i tried my best to match the existing color theme
Changes:
- memorize coordinates from geoJSON
- formatting the float to be 4 values after the comma
- conditional render if the extraction of values works it shows the new box otherwise it reverts to the old behaviour
Motivation:
- clarity for the user when it comes to the geo viewer as the issue stated
- made the changes locally in the GeographyDrawer and stayed away from changing deeper geoJSON behaviour in /util/surrealql
=> Changes to Longitude Latitude in GeographyDrawer

src/components/GeographyDrawer/index.tsx
This PR implements a few minor changes to the recent geography pull request
=> Implement minor adjustments to geo changes

src/constants.tsx, src/screens/surrealist/views/query/ResultPane/index.tsx
CSV Exporting was broken in the desktop app. This PR uses the adapter for saving csv files.
=> Use adapter for csv exports
