src/views/designer/StructurePane/helpers.tsx
src/views/designer/StructurePane/inputs.tsx

This fixes #45 by not automatically adding `WHERE ${value})`, and adding a placeholder

Make permissions input idempotent and add placeholder

---

src/adapter/desktop.tsx

Added guard clause for fetchSchema() (Desktop)
**RCA**: When the database has no tables `fetchSchema()` triggeres `surreal.query()` with an empty string as a method that throws an Exception that blocks refreshing and deleting tables from UI.
fixes #65

(fix): Added guard clause for fetchSchema() (Desktop)

---

src-tauri/src/schema.rs

I made the Tauri schema methods async to prevent ui freezing issues
This should fix the UI freezing completely as seen in #71. 
I tested these locally on my Ubuntu system and it looks like everything is working, at least from my testing
When using the large payload from #71, the UI doesn't freeze anymore.

fix: :zap: Mark schema methods async

---

src/adapter/desktop.tsx

The logic introduced in https://github.com/StarlaneStudios/Surrealist/commit/cfa4573770c93e28f90c344ca401103160076066 was supposed to be the other way around.
I replaced this logic with a regex, which will only replace "ws" from only the beginning of the endpoint with "http".

Replace ws -> http rather than http -> ws; Also replace wss; Only replace from start of string

---

src/views/authentication/ScopesPane/index.tsx

There was a typo in scope pane view that sends `SIGNIN` twice instead `SIGNUP`

FIX issue #219

---

src/adapter/mini.tsx
src/components/Pane/index.tsx
src/components/Scaffold/settings/tabs/Appearance.tsx
src/constants.tsx
src/mini/new.tsx
src/types.tsx
src/util/defaults.tsx
src/views/query/QueryView/index.tsx
src/views/query/ResultPane/index.tsx
src/views/query/ResultPane/style.module.scss

This PR introduces a new setting which allows customising the orientation of the query view. Most importantly, this allows for displaying queries and results side-by-side similar to Surrealist 1.x.

Customize query view orientation

---

package.json

* add conventional script to use `npm start` command
* reorder scripts alphabetically

chore: add conventional "start" script

---

src/connection.tsx
src/util/helpers.tsx
src/util/version.tsx

- Check version using /rpc and fallback to /version
- Show a warning when the version cannot be determined
- Allow for connecting to SurrealDB hosted on sub-paths
- Awaiting new version of surrealdb.js

Improve connection logic

---

src-tauri/src/config.rs

Using jsonxf to pretty print config.json when saving.

feature: Have config.json pretty printed

---

.eslintrc
package.json
pnpm-lock.yaml
src/components/App/index.tsx
src/components/Pane/index.tsx
src/views/explorer/ExplorerPane/index.tsx

Fix loading of records, especially when switching tables that takes some time to load.
* Add `@tanstack/react-query` and `@tanstack/eslint-plugin-query` packages
* `useQuery` to simplify the loading logic of records (having `isLoading`, `data` and `refresh` properties already available)
* use `LoadingOverlay` from mantime when records are loading
Example:

fix: fix loading of records in explorer view

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/config.rs

It is necessary to use serde_json::from_str to convert the config str into a serde_json::Value then use serde_json::to_string_pretty to get a proper pretty printed result.
This costs an additional line of code and an unknown performance difference, but it does reduce
the number of dependencies by 3 removing getopts, jsonxf and unicode-width. I also results in
a very slight reduction in the release binary. For jsonxf the size was 27,679,424 compared to serde_json at
27,661,224. Which is 18,200 bytes but as a percentage it's tiny at (18200/27661224)*100 = 0.0658%.
Here is the data.
```
$ find . -type f -name 'surrealist' -print0 | xargs -0 stat --format="%s %n"
265382360 ./src-tauri/target-main-using-jsonxf/debug/surrealist
27679424 …
```

feature: Pretty print using serde_json correctly

---

src/components/NavigationIcon/index.tsx
src/components/Scaffold/index.tsx
src/constants.tsx
src/hooks/hover-icon.ts
src/views/authentication/AuthenticationView/index.tsx
src/views/designer/DesignerView/index.tsx
src/views/designer/TableGraphPane/helpers.tsx
src/views/documentation/DocumentationView/index.tsx
src/views/explorer/ExplorerView/index.tsx
src/views/functions/FunctionsView/index.tsx
src/views/models/ModelsView/index.tsx
src/views/query/QueryPane/index.tsx
src/views/query/QueryView/index.tsx
vite.config.ts

Use code-splitting techniques to reduce initial bundle size and to improve startup time performance.
Improvements made:
* lazy import page components (Query view, Explorer view, etc...)
* lazy import of modules, like `lottie-web`. It will be fetched on the main page but after the initial bundles
* lazy import json animated data for lottie
Some notes:
* `elk` can be loaded via web worker, but as it is currently lazy imported when needed, I don't see the need for this
* bundle size reduced by using `lottie-light` instead of `lottie-web`, from 7.27MB to 7.04MB (1.83MB -> 1.79MB gzip)
* some vendors cannot be easily lazy imported (e.g. codemirror) => use `manualChunks` to split each bundle
* splitting in chunks can improve load times by preloading modules in parallel instead of waiting for a …

chore: use code-splitting techniques

---

src/adapter/desktop.tsx
src/assets/changelogs/2.1.0.md
src/components/Scaffold/settings/tabs/Appearance.tsx
src/components/Scaffold/settings/tabs/Templates.tsx
src/components/Scaffold/settings/utilities.tsx
src/types.tsx
src/util/defaults.tsx
src/views/designer/TableGraphPane/helpers.tsx
src/views/designer/TableGraphPane/index.tsx
src/views/designer/TableGraphPane/style.module.scss
src/views/explorer/ExplorerPane/index.tsx

Adds a new setting to the designer view to visualize record links between tables
- Disabled by default as it adds significant complexity to the designer graph
- Configurable per connection and new setting to configure default value
- Multiple overlapping links are collapsed into a single line
closes #100

Implement Designer view record link visualization

---

src/screens/database/views/query/QueryPane/index.tsx

I noticed a small typo in the query pane so I decided to come fix it myself. It used to be 'selecion' and is now 'selection'

fix: typo in query pane

---

src/components/CodeEditor/index.tsx
src/components/CodePreview/index.tsx
src/components/Inputs/index.tsx
src/util/editor/extensions.tsx

Closes https://github.com/surrealdb/surrealist/issues/340
Theme in terms of "dark" or "light" doesn't seem to work well with CodeMirror - for some reason `themeType` is not set as state, but based on what theme extension was added (if I understand codemirror source correctly).
That's why I refactored theme into it's own `Compartment`.

Fix: light theme

---

package.json
pnpm-lock.yaml
src/adapter/browser.tsx
src/util/idxdb.ts
src/util/storage.tsx

* save config in IndexedDb to avoid storage constraint and improve app performance (async storage)
* simple transition from localstorage to IndexedDb
* use `idb` package to simplify IndexedDb usage (1.2kB gzipped)

feat: save config in indexeddb

---

.vscode/tasks.json
package.json
pnpm-lock.yaml
src/components/ActionButton/index.tsx
src/screens/database/components/TablesPane/index.tsx
src/screens/database/views/designer/DesignerView/index.tsx
src/screens/database/views/designer/TableGraphPane/index.tsx
src/screens/database/views/explorer/ExplorerPane/index.tsx
src/screens/database/views/explorer/ExplorerView/index.tsx
src/screens/database/views/query/QueryPane/index.tsx
src/screens/database/views/query/QueryView/index.tsx
src/screens/database/views/query/TabsPane/index.tsx
src/types.tsx
src/util/defaults.tsx

- This PR brings the Query and Explorer views in line with the Designer view which already supports this functionality.
- The explorer tables panel will always be displayed when no table is selected

Add table and query panel collapsing

---

src/screens/database/components/ConnectionStatus/index.tsx

This pull request adds a simple button to the connection dropdown menu which syncs the schema. This is useful when tables or other resources have been created externally and need to be updated inside of Surrealist.

feat: add sync schema button

---

src/screens/database/components/TablesPane/index.tsx
src/screens/database/views/designer/DesignerView/index.tsx
src/screens/database/views/designer/TableGraphPane/index.tsx
src/util/intents.tsx

- Allows focusing a table in the table graph
- Exposed as a new `focus-table` intent
- Also added an animation to "Fit viewport"
Closes #498

Add focus table context menu option

---

src/editor/keymaps.tsx
src/editor/query.tsx
src/editor/selection.tsx
src/editor/surrealql.tsx
src/screens/database/connection/connection.tsx
src/screens/database/views/query/QueryPane/index.tsx
src/screens/database/views/query/QueryView/index.tsx

Added `Cmd/ctrl + E` to SurrealQL editors to select the query your cursor is located in. This is especially useful useful when combined with `Cmd/ctrl + Enter` to execute the selected query.

Add editor shortcut to select the current query

---

src/screens/cloud-manage/pages/Billing/index.tsx

the invoice Amount is reported in cents, the way to convert cents to full units is to divide by 100 not multiply by 100,
example: 350 cents = 3.50 USD (350/100)
example of invoices that look off:

[fix] correctly convert cents to unit

---

src/components/App/modals/signup.tsx

Updates the text shown under the `Value` column in the `Register with access method` dialog to use `field.value` instead of `field.subject`
Fixes #562

Fix Signup dialog using subject instead of value

---

src/components/CodeEditor/index.tsx
src/editor/helpers.tsx
src/editor/surrealql.tsx
src/screens/database/connection/connection.tsx
src/screens/database/views/query/HistoryDrawer/index.tsx
src/screens/database/views/query/QueryPane/index.tsx
src/screens/database/views/query/QueryView/index.tsx
src/screens/database/views/query/ResultPane/index.tsx
src/screens/database/views/query/SavesDrawer/index.tsx
src/screens/database/views/query/TabsPane/index.tsx
src/screens/database/views/query/VariablesPane/index.tsx
src/stores/query.tsx
src/util/global-events.tsx
src/util/messaging.tsx

- Refactor `CodeEditor` to support updating and restoring editor state
- Editor state is serialised into the store, and saved per-query
- Overhauled the inner workings of `CodeEditor` to simplify compartments
- Moved query reading logic into the `QueryPane`
- Remove editor state when the query is closed
- Added a callback to the SurrealQL linter

Separate query editing history 

---

src/components/Inputs/index.tsx

This PR fixes an incorrect placeholder text in the PermissionInput component where "WHERE" is included by mistake. This makes it appear as though you should be entering "WHERE" in your permissions string, however it is not required and actually would result in an error since "WHERE" is being placed in front of the permissions string by default.

fix: improper placeholder text on the permissions input

---

src/screens/surrealist/views/designer/TableGraphPane/index.tsx

This PR fixes issue #634, in which the graph option menu appears at the top left of the page.

fix: issue #634

---

src/screens/surrealist/views/explorer/ExplorerPane/index.tsx

There was an incorrect fallback value defined causing the Explorer view to sometimes not allow revealing the table list
Fixes #632

Fix missing explorer reveal button

---

src/screens/surrealist/cloud-panel/components/Instance/index.tsx

This PR changes the text of the Surreal Cloud delete instance modal from 'Deleting' to 'Delete' since the instance is not being deleted yet.

Fix a very minor typo in the Delete Instance modal

---

src/screens/surrealist/views/explorer/ExplorerPane/index.tsx

Simple change to make the row count under the explorer view more readable.

Use locale number format for rows counter

---

src/util/preferences.tsx

This PR fixes a bug with the cloud endpoints feature flag which caused the endpoints preferences to show by default

fix: cloud endpoints showing on prefs page by default

---

src/components/Sidekick/index.tsx

This PR fixes a very minor grammar issue in the sidekick view where the disclaimer used a comma instead of a period

fix: sidekick disclaimer grammar

---

src/cloud/modals/connect-cli.tsx
src/cloud/mutations/auth.tsx
src/cloud/queries/backups.tsx
src/components/InstanceActions/index.tsx

There is not an easy way for to copy an auth token of a cloud instance in Surrealist. You have to open an CLI modal and then manually select the token field which can be painful.
This PR makes sure you can copy the auth token in 2 clicks on the overview page of the cloud instance.

Improve UX for copying auth token

---

Makefile

Small change to fix the Makefile which was using a non-existent target as a dependency of the `serve` target.

Fix broken `serve` make target

---

src/screens/surrealist/pages/OrganizationManage/tabs/billing.tsx

Currently errors are not handled. This will be improved in a followup PR improving the showError function

Show error on payment url failure

---

public/instance.json
src/adapter/docker.tsx
src/schemas.tsx
src/util/feature-flags.tsx

Removed the readonly status of cloud endpoints to ease internal testing, and also allow enabling cloud functionality in self hosted docker environments

Fix readonly cloud endpoints and improve docker support

---

src/components/InstanceTypes/index.tsx
src/screens/surrealist/pages/CreateInstance/steps/storage-class.tsx
src/screens/surrealist/views/dashboard/ConfigurationBlock/index.tsx
src/util/cloud.tsx

This PR fixes the incorrect distributed instance type for memory intensive instances (production) and changes it to the correct type (production-memory). This PR also fixes another issue with distributed instances where selecting the advanced storage class and setting the storage size to 6TB fails to revert to the maximum of 1TB when reverting back to standard, causing a failed API request.

Fix distributed instance type and storage issues

---

.aws/beta/viewer-request/Makefile
.aws/dev/viewer-request/Makefile
.aws/prod/origin-request/Makefile
.aws/prod/viewer-request/Makefile
LICENSE
Makefile
src/components/App/settings/tabs/About.tsx

This PR makes a few small changes in which the 2024 copyright year is updated to 2025 in multiple places. Additionally, this PR implements a dynamic year which always displays the current year in the about page, ensuring that the copyright is always up to date there.

Bump copyright year

---

src/components/SaveBox/index.tsx
src/hooks/save.ts
src/providers/Designer/drawer.tsx
src/providers/Designer/index.tsx
src/providers/Inspector/drawer.tsx
src/providers/Inspector/tabs/content.tsx
src/screens/surrealist/views/functions/EditorPanel/index.tsx

This PR adds an apply button next to the save button which applies changes but doesn't close the drawer in the record inspector and table designer.
Closes #779

Allow saving records and tables without closing inspector

---

src/providers/Inspector/style.module.scss

This PR fixes a bug where large IDs would overflow to the next line without resizing the input box, causing them to be cut off.
Closes #793

Fix large IDs overflowing

---

src/components/Pagination/index.tsx

This PR fixes a bug in which your current page in the explorer view can be above the total number of pages, caused usually when all records are deleted on a page without switching to another page.
Closes #806

Fix page being out of range in explorer view

---

src/screens/surrealist/components/DatabaseList/index.tsx
src/screens/surrealist/components/NamespaceList/index.tsx
src/screens/surrealist/connection/connection.tsx
src/screens/surrealist/views/explorer/ExplorerView/index.tsx
src/util/global-events.tsx
src/util/schema.tsx

- Display a loading indicator as the schema is being retrieved
- Align namespace and database dropdowns to the left to prevent content shift
- Reset the explorer view when the connection, namespace, or database changes
Closes #807

Improve namespace and database selection behavior

---

src/cloud/hooks/confirm.tsx
src/components/DataTable/index.tsx
src/hooks/cloud.tsx
src/hooks/updater.tsx
src/providers/Confirmation/index.tsx
src/providers/Designer/drawer.tsx
src/providers/Inspector/drawer.tsx
src/screens/surrealist/components/DatabaseList/index.tsx
src/screens/surrealist/components/NamespaceList/index.tsx
src/screens/surrealist/components/TablesPane/index.tsx
src/screens/surrealist/pages/OrganizationManage/tabs/team.tsx
src/screens/surrealist/pages/Organizations/organization.tsx
src/screens/surrealist/views/authentication/LevelPanel/index.tsx
src/screens/surrealist/views/explorer/ExplorerPane/index.tsx
src/screens/surrealist/views/functions/FunctionsView/index.tsx
src/screens/surrealist/views/parameters/ParametersView/index.tsx
src/screens/surrealist/views/query/QueryPane/index.tsx
src/types.tsx
src/util/defaults.tsx
src/util/preferences.tsx

This PR adds several improvements:
- Makes the query execution warning able to be hidden temporarily (until view refresh)
- Makes confirmations skippable (except for some specific ones that are extra important)
- Add an indexed icon to the explorer view columns to show which columns are indexed
- Add a preference to use enter to confirm in modals
Closes #799
Closes #797

Misc improvements and changes

---

src/screens/surrealist/views/dashboard/ConfiguratorDrawer/capabilities/registry.tsx

This HTTP endpoint is always enabled on Surreal Cloud instances

Remove status option

---

src/screens/surrealist/views/query/ResultPane/previews/graph.tsx
src/screens/surrealist/views/query/ResultPane/previews/individual.tsx
src/screens/surrealist/views/query/ResultPane/previews/table.tsx

Closes #955 - Bug: Unable to select/copy text when result is an error

Fix: Allow users to select error text

---

src/screens/surrealist/pages/OrganizationDeploy/sections/instance.tsx

Fixes a problem where organisations could select any region to deploy instead of the regions they had access to, resulting in an error on deployment.

Fix use of all regions instead of supported regions in cloud
